server:
  port: 8094

filter:
  white-list: /users/login,/users/register,/swagger-resources,/v2/api-docs,/folder/upload,/folder/recordFiles,/keepFiles/,/imageFiles/,/recordFiles/,/logFiles/,/packageFiles/
  resetToken: true

spring:
  cloud:
    gateway:
      routes:
        - id: controller
          uri: lb://sonic-server-controller
          predicates: Path=/api/controller/**
          filters:
            - StripPrefix=2
        - id: folder
          uri: lb://sonic-server-folder
          predicates: Path=/api/folder/**
          filters:
            - StripPrefix=2
        - id: task
          uri: lb://sonic-server-task
          predicates: Path=/api/task/**
          filters:
            - StripPrefix=2
        - id: transport
          uri: lb://sonic-server-transport
          predicates: Path=/api/transport/**
          filters:
            - StripPrefix=2
        - id: bus
          uri: lb://sonic-server-bus
          predicates: Path=/api/bus/**
          filters:
            - StripPrefix=2